### ISSUE TITLE
Write a .NET SDK for merchants

### ISSUE THREAD

**Issue by ruphy** [italia/18app-dotnet-sdk#1]
The documentation, test files and a description of the test environment are available here:

[Progetto18app.zip](https://github.com/italia/18app-dotnet-sdk/files/1356869/Progetto18app.zip)
[WS_VerificaVoucher.zip](https://github.com/italia/18app-dotnet-sdk/files/1356870/WS_VerificaVoucher.zip)
[Linee Guida Esercenti_ottobre 2016.pdf](https://github.com/italia/18app-dotnet-sdk/files/1356867/Linee.Guida.Esercenti_ottobre.2016.pdf)

**Comment by sklivvz** [comment]
is this dotnet or dotnet-core?

**Comment by ruphy** [comment]
Hi,
dotnet-core is preferred, in this case

**Comment by alranel** [comment]
Qui spiegazioni su 18app: https://developers.italia.it/it/18app/

**Comment by sklivvz** [comment]
@ruphy dotnet-core non ha supporto per xml web service, quindi ho fatto dotnet 4.6. Se e quando avremo servizi JSON e' un attimo supportarli con dotnet-core.
